---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: modify-vm-template-taskrun
spec:
  serviceAccountName: modify-vm-template-task
  taskRef:
    kind: ClusterTask
    name: modify-vm-template
  params:
  - name: templateName
    value: vm-template-example
