apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: windows10-customize-run-
spec:
  params:
  - name: sourceDataVolumeName
    value: INSERT_NAME_OF_SOURCE_DATAVOLUME
  - name: sourceDataVolumeNamespace
    value: INSERT_NAMESPACE_OF_SOURCE_DATAVOLUME
  pipelineRef:
    name: windows10-customize
  taskRunSpecs:
    - pipelineTaskName: create-base-dv
      taskServiceAccountName: create-data-object-task
    - pipelineTaskName: create-vm-from-manifest
      taskServiceAccountName: create-vm-from-manifest-task
    - pipelineTaskName: wait-for-vmi-status
      taskServiceAccountName: wait-for-vmi-status-task
    - pipelineTaskName: cleanup-vm
      taskServiceAccountName: cleanup-vm-task
status: {}
