---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: {{ item.taskrun_with_flavor_name }}
spec:
  serviceAccountName: {{ sa_name }}
  taskRef:
    kind: ClusterTask
    name: {{ item.subtask_name }}
{% if item.type == "from-template-simple" %}
  params:
  - name: templateName
    value: vm-template-example
  - name: templateParams
    value:
      - 'NAME:example-vm'
  - name: ownDataVolumes
    value:
      - example-dv
{% else %}
  params: []
{% endif %}
