---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: {{ item }}
spec:
{% if task_yaml.metadata.annotations['task.kubevirt.io/associatedServiceAccount'] is defined %}
  serviceAccountName: {{ sa_name }}
{% endif %}
  taskRef:
    kind: Task
    name: {{ task_name }}
  params:
    - name: pvc
      value: example-pvc
    - name: sysprepCommands
      value: |
        update
        install make,ansible
        operations firewall-rules,defaults
