---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  annotations:
    task.kubevirt.io/associatedServiceAccount: copy-template-task
    sourceTemplateName.params.task.kubevirt.io/type: vm-template-name
    sourceTemplateName.params.task.kubevirt.io/kind: Template
    sourceTemplateName.params.task.kubevirt.io/apiVersion: template.openshift.io/v1
    sourceTemplateNamespace.params.task.kubevirt.io/type: namespace
    sourceTemplateParams.params.task.kubevirt.io/type: template-params-array
    targetTemplateName.params.task.kubevirt.io/type: vm-template-name
    targetTemplateName.params.task.kubevirt.io/kind: Template
    targetTemplateName.params.task.kubevirt.io/apiVersion: template.openshift.io/v1
    targetTemplateNamespace.params.task.kubevirt.io/type: namespace
    targetTemplateParams.params.task.kubevirt.io/type: template-params-array
  labels:
    task.kubevirt.io/type: copy-template
    task.kubevirt.io/category: copy-template
  name: copy-template
spec:
  params:
    - name: sourceTemplateName
      description: Name of an OKD template to copy template from.
      type: string
    - name: sourceTemplateNamespace
      description: Namespace of an source OKD template to copy template from. (defaults to active namespace)
      type: string
    - name: targetTemplateName
      description: Name of an target OKD template.
      type: string
    - name: targetTemplateNamespace
      description: Namespace of an target OKD template to create in. (defaults to active namespace)
      type: string
  results:
    - name: name
      description: The name of a template that was created.
    - name: namespace
      description: The namespace of a template that was created.
  steps:
    - name: copytemplate
      image: quay.io/kubevirt/tekton-task-copy-template:v0.0.1
      command:
        - copy-template
      args:
        - "--output=yaml"
        - '--source-template-name'
        - $(params.sourceTemplateName)
        - '--source-template-namespace'
        - $(params.sourceTemplateNamespace)
        - '--target-template-name'
        - $(params.targetTemplateName)
        - '--target-template-namespace'
        - $(params.targetTemplateNamespace)
      env:
        - name: SOURCE_TEMPLATE_NAME
          value: $(params.sourceTemplateName)
        - name: SOURCE_TEMPLATE_NAMESPACE
          value: $(params.sourceTemplateNamespace)
        - name: TARGET_TEMPLATE_NAME
          value: $(params.targetTemplateName)
        - name: TARGET_TEMPLATE_NAMESPACE
          value: $(params.targetTemplateNamespace)

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: copy-template-task
rules:
  - verbs:
      - get
      - list
      - watch
      - create
    apiGroups:
      - template.openshift.io
    resources:
      - templates

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: copy-template-task

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: copy-template-task
roleRef:
  kind: ClusterRole
  name: copy-template-task
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: copy-template-task
