---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: disk-virt-customize-taskrun
spec:
  taskRef:
    kind: ClusterTask
    name: disk-virt-customize
  params:
    - name: pvc
      value: example-pvc
    - name: script
      value: |
        update
        install make,ansible
        delete /var/cache/dnf
