apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: windows10-installer-run-
spec:
  params:
  - name: winImageDownloadURL
    value: INSERT_WINDOWS_ISO_URL
  pipelineRef:
    name: windows-bios-installer
  taskRunSpecs:
    - pipelineTaskName: create-source-dv
      taskServiceAccountName: modify-data-object-task
    - pipelineTaskName: create-base-dv
      taskServiceAccountName: modify-data-object-task
    - pipelineTaskName: create-vm-from-manifest
      taskServiceAccountName: create-vm-from-manifest-task
    - pipelineTaskName: wait-for-vmi-status
      taskServiceAccountName: wait-for-vmi-status-task
    - pipelineTaskName: cleanup-vm
      taskServiceAccountName: cleanup-vm-task
status: {}
