---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  annotations:
    pvc.params.task.kubevirt.io/kind: PersistentVolumeClaim
    pvc.params.task.kubevirt.io/apiVersion: v1
    script.params.task.kubevirt.io/type: script
  labels:
    task.kubevirt.io/type: disk-virt-customize
    task.kubevirt.io/category: disk-virt-customize
  name: disk-virt-customize
spec:
  params:
    - name: pvc
      description: PersistentVolumeClaim to run the the virt-customize script in. PVC should be in the same namespace as taskrun/pipelinerun.
      type: string
    - name: script
      description: virt-customize script in "--commands-from-file" format.
      type: string
  steps:
    - name: run-virt-customize
      image: quay.io/kubevirt/tekton-task-disk-virt-customize:v0.0.1
      command:
        - entrypoint
      env:
        - name: EXECUTE_SCRIPT
          value: $(params.script)
      volumeMounts:
        - mountPath: /data/targetpvc/
          name: targetpvc
  volumes:
    - name: targetpvc
      persistentVolumeClaim:
        claimName: $(params.pvc)
