---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: virt-sysprep-updater-run-
spec:
  pipelineRef:
    name: virt-sysprep-updater
  taskRunSpecs:
    - pipelineTaskName: create-data-object
      taskServiceAccountName: create-data-object-task
    - pipelineTaskName: create-vm-from-manifest
      taskServiceAccountName: create-vm-from-manifest-task
