---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: virt-sysprep-updater-run-
spec:
  pipelineRef:
    name: virt-sysprep-updater
  serviceAccountNames:
    - taskName: create-data-object
      serviceAccountName: create-data-object-task
    - taskName: create-vm-from-manifest
      serviceAccountName: create-vm-from-manifest-task
