---
- connection: local
  hosts: 127.0.0.1
  gather_facts: no
  vars_files:
    - ../../configs/create-vm.yaml
    - ../../scripts/ansible/enums.yaml
  vars:
    output_dir: ./dist
    manifests_output_dir: "{{ output_dir }}/manifests"
    examples_output_dir: "{{ output_dir }}/examples"
    examples_taskruns_output_dir: "{{ examples_output_dir }}/taskruns"
    manifest_templates_dir: ./manifests
    examples_templates_dir: ./examples
    readmes_templates_dir: ./readmes
    repo_dir: ../..
    role_name: "{{ task_name }}-task"
    sa_name: "{{ role_name }}"
    role_binding_name: "{{ role_name }}"
    default_file_mode: "0644"
    # subtasks
    create_vm_from_template_name: "{{ task_name }}-from-template"
  tasks:
    - name: Clean dist directory
      file:
        path: "{{ manifests_output_dir }}"
        state: absent
    - name: Prepare dist directory
      file:
        path: "{{ manifests_output_dir }}"
        state: directory
    - name: Generate create-vm task
      template:
        src: "{{ manifest_templates_dir }}/{{ task_name }}.yaml"
        dest: "{{ manifests_output_dir }}/{{ item.task_with_flavor_name }}.yaml"
        mode: "{{ default_file_mode }}"
      with_items:
        - { task_type: Template, task_with_flavor_name: "{{ create_vm_from_template_name }}" }
    - name: Generate roles
      include: "{{ repo_dir }}/scripts/ansible/generate-roles-subtasks.yaml"
      with_items:
        - { role_type: Role, role_id: 'namespace', sa_namespace: null }
        - { role_type: ClusterRole, role_id: 'cluster', sa_namespace: 'TARGET_NAMESPACE' }
      vars:
        role_output_dir: "{{ manifests_output_dir }}"
    - name: Prepare examples dist directory
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ examples_output_dir }}"
        - "{{ examples_taskruns_output_dir }}"
    - name: Generate example task runs
      template:
        src: "{{ examples_templates_dir }}/{{ task_name }}-taskrun.yaml"
        dest: "{{ examples_taskruns_output_dir }}/{{ item.taskrun_with_flavor_name }}.yaml"
        mode: "{{ default_file_mode }}"
      with_items:
        - { type: "from-template-simple", subtask_name: "{{ create_vm_from_template_name }}", taskrun_with_flavor_name: "{{ create_vm_from_template_name }}-taskrun" }
    - name: Generate README
      template:
        src: "{{ readmes_templates_dir }}/README.md"
        dest: "{{ output_dir }}/README.md"
        mode: "{{ default_file_mode }}"
      vars:
        create_vm_from_template_path: "{{ manifests_output_dir }}/{{ create_vm_from_template_name }}.yaml"
        create_vm_from_template_yaml: "{{ lookup('file', create_vm_from_template_path) | from_yaml }}"
